steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/business-transformers/vatan1-cloud-run-continuous-deployment-example:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/business-transformers/vatan1-cloud-run-continuous-deployment-example:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'vatan1-cloud-run-continuous-deployment-example', '--image=gcr.io/business-transformers/vatan1-cloud-run-continuous-deployment-example:$SHORT_SHA', '--region=asia-south1']
  
