steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/business-transformers/my-source-repo-suchita@sha256:1e94a31312ec56ba1d519ad3d16cc8c909d7323cfa38bd0924aba33272c0ecdb || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/business-transformers/my-source-repo-suchita@sha256:1e94a31312ec56ba1d519ad3d16cc8c909d7323cfa38bd0924aba33272c0ecdb',
   '-t', 
   'gcr.io/business-transformers/my-source-repo-suchita@sha256:1e94a31312ec56ba1d519ad3d16cc8c909d7323cfa38bd0924aba33272c0ecdb',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-vatan'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'my-source-repo-suchita', 
   'my-source-repo-suchita=gcr.io/business-transformers/my-source-repo-suchita@sha256:1e94a31312ec56ba1d519ad3d16cc8c909d7323cfa38bd0924aba33272c0ecdb'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-vatan'

