steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/business-transformers/vatan2-cloud-run-continuous-deployment-example:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/business-transformers/vatan2-cloud-run-continuous-deployment-example:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env: ['CLOUDSDK_COMPUTE_REGION='asia-south1-c' , 'CLOUDSDK_CONTAINER_CLUSTER='cluster-vatan']
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'vatan2-cloud-run-continuous-deployment-example', 
   'vatan2-cloud-run-continuous-deployment-example'='gcr.io/business-transformers/vatan2-cloud-run-continuous-deployment-example:$SHORT_SHA'
  ]
  env:
   - 'CLOUDSDK_COMPUTE_REGION='asia-south1-c'
   - 'CLOUDSDK_CONTAINER_CLUSTER='cluster-vatan'  
  
  
  
  
 #
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['beta', 'run', 'deploy', 'vatan2-cloud-run-continuous-deployment-example', '--image=gcr.io/business-transformers/vatan2-cloud-run-continuous-deployment-example:$SHORT_SHA', '--region=asia-south1']
#- name: "gcr.io/cloud-builders/gke-deploy1"
#  args:
#  - run
#  - --filename=gke-app.yaml
#  - --image=gcr.io/business-transformers/vatan2-cloud-run-continuous-deployment-example:$SHORT_SHA'
#  - --location=asia-south1
#  - --cluster=autopilot-cluster-v


