steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/business-transformers/my-source-repo-suchita:374c2cff6ca81d48f4ea92d81e350aaa941298ab || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/business-transformers/my-source-repo-suchita:374c2cff6ca81d48f4ea92d81e350aaa941298ab',
   '-t', 
   'gcr.io/business-transformers/my-source-repo-suchita:374c2cff6ca81d48f4ea92d81e350aaa941298ab',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'app.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-vatan'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'my-source-repo-suchita', 
   'my-source-repo-suchita=gcr.io/business-transformers/my-source-repo-suchita:374c2cff6ca81d48f4ea92d81e350aaa941298ab'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-vatan'

