kind: Service
apiVersion: v1
metadata:
  name: my-source-repo-suchita
spec:
  selector:
     run: my-source-repo-suchita
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 80
  type: LoadBalancer
